# Site settings
title: Radimir Bitsov
description: 'My personal web space'
url: 'http://radibit.com'
twitter_username: radibit
github_username:  radibit

# Exclude
exclude:
  - package.json
  - node_modules
  - gulpfile.js

# Build settings
markdown: kramdown
