# Site settings
title: Radimir Bitsov - Web Development
description: 'The personal web space of Radimir Bitsov'
url: 'https://www.radibit.com'
twitter_username: radibit
github_username:  radibit

# Exclude
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown

gems:
  - jemoji
